name: Deploy

on:
  # 推送到 main 分支时触发
  push:
    branches:
      - main
      - test
  # 允许手动触发
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      # 根据分支判断环境
      - name: Set Deploy Environment
        run: |

          if [ "${{ github.ref }}" = "refs/heads/main" ]; then

            echo "ENV=production" >> $GITHUB_ENV
            echo "DEPLOY_PATH=/www/wwwroot/vue/vue-prod/" >> $GITHUB_ENV


          else

            echo "ENV=test" >> $GITHUB_ENV
            echo "DEPLOY_PATH=/www/wwwroot/vue/vue-test/" >> $GITHUB_ENV

          fi

      
      - name: Configure npm authentication
        run: |
          echo "registry=https://packages.aliyun.com/5faa3678e6f9d07f148517ac/npm/npm-registry/" > .npmrc
          echo "//packages.aliyun.com/5faa3678e6f9d07f148517ac/npm/npm-registry/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc


      - name: Configure npm authentication
        run: |
            echo "registry=https://packages.aliyun.com/5faa3678e6f9d07f148517ac/npm/npm-registry/" > .npmrc
            echo "//packages.aliyun.com/5faa3678e6f9d07f148517ac/npm/npm-registry/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc


      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Alibaba Cloud
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/*"
          target: "${{ env.DEPLOY_PATH }}"


      - name: Success notification
        if: success()
        run: |
          echo "========================================="
          echo "🎉 部署成功！"
          echo "========================================="
